# Generated by Django 6.0.6 on 2026-06-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='emrolled_at',
            new_name='enrolled_at',
        ),
    ]
